name: Generate Week Index

on:
  workflow_run:
    workflows: ["Scrape Curling Data Weekly"]
    types:
      - completed

permissions:
  contents: write

jobs:
  generate-index:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository at triggering commit
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate index.json
        run: |
          find public/data -name "curling_data_week_*.csv" | \
            sed 's/.*week_\([0-9]*\).csv/\1/' > weeks.txt

          echo '{"weeks":[' > public/data/index.json
          awk '{print "\"" $1 "\","}' weeks.txt | sed '$s/,$//' >> public/data/index.json
          echo ']}' >> public/data/index.json

      - name: Commit and push changes
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet public/data/index.json; then
            git add public/data/index.json
            git commit -m "Auto-generated index.json"
            git push
            echo "DEPLOY_NEEDED=true" >> $GITHUB_ENV
          else
            echo "No changes to index.json, skipping commit & deploy."
            echo "DEPLOY_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        if: env.DEPLOY_NEEDED == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        if: env.DEPLOY_NEEDED == 'true'
        run: npm ci

      - name: Deploy to GitHub Pages
        if: env.DEPLOY_NEEDED == 'true'
        run: npm run deploy
