name: Generate Week Index

on:
  workflow_run:
    workflows: ["Scrape Curling Data Weekly"]
    types:
      - completed

jobs:
  generate-index:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate index.json
        run: |
          find public/data -name "curling_data_week_*.csv" | \
            sed 's/.*week_\([0-9]*\).csv/\1/' > weeks.txt

          echo '{"weeks":[' > public/data/index.json
          awk '{print "\"" $1 "\","}' weeks.txt | sed '$s/,$//' >> public/data/index.json
          echo ']}' >> public/data/index.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public
